### ISSUE TITLE
EOD Suit Helmet Light is not fully tracking head movements

### ISSUE THREAD

**Issue by Grezvany13** [Grezvany13/AExt#1]
The lights on the helmet are "sort of" working, but still needs tweaking in calculating the correct directions (horizontal and vertical) to match the head/eye movements.

- [ ] **Yaw**: using `CBA_fnc_headDir`, but seems to return very strange values
- [ ] **Pitch**: using `eyePos` and `eyeDirection`, but calculations are wrong
- [ ] **Roll**: most likely can't be done due to engine limitations

Files:
- https://github.com/Grezvany13/AExt/blob/master/addons/eod/scripts/fn_lights.sqf
